// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.ProgrammingLaptop1Steamworks2017.subsystems;

import org.usfirst.frc692.ProgrammingLaptop1Steamworks2017.Robot;
import org.usfirst.frc692.ProgrammingLaptop1Steamworks2017.RobotMap;
import org.usfirst.frc692.ProgrammingLaptop1Steamworks2017.commands.*;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Climber extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid climberSolenoid = RobotMap.climberClimberSolenoid;
    private final SpeedController climber = RobotMap.climberClimber;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void climberUp()
    {
    	if (Robot.oi.climbUpButtonLB.get() == true)
    	{
    		climber.set(1.0);
    		SmartDashboard.putString("climbUp:", "true");
    	}
    	else
    	{
    		SmartDashboard.putString("climbUp:", "false");
    	}
    }
    // Give motor 100% power up to climb up.
    // APO 1/26/17
    
    public void climberStop()
    {
    	climber.set(0.0);
    }
    // When button is not pressed don't do anything.
    // APO 1/26/17
    
    
    public void climberDown()
    {
    	if (Robot.oi.climbDownButtonRB.get() == true)
    	{
    		climber.set(-1.0);
    		SmartDashboard.putString("climbDown:", "true");
    	}
    	else
    	{
    		SmartDashboard.putString("climbDown:", "false");
    	}
    }
    // Give motor 100% power to climb down
    // APO 2/7/17
    
    
    public void retract()
    {
    	SmartDashboard.putString("button 8 is pressed", "true");
    	climberSolenoid.set(Value.kReverse);
    }
    // Causes piston to close therefore the gear mechanism opens to release the gear in it.
    // APO 1/21/2017
    
    public void reset()
    {
    	climberSolenoid.set(Value.kOff);
    }
    //air is turned off on gear mechanism
    //gearSolenoid can now reset itself
    //APO 1/21/2017
    
    public void extendOut()
    {
    	SmartDashboard.putString("button 7 is pressed", "false");
    	climberSolenoid.set(Value.kForward);
    }
    // Causes piston to open therefore the gear mechanism closes and the gear is held in place.
    // APO 1/21/2017
}

